erDiagram
    %% DIMENSIONES
    BI_DIM_TIEMPO {
        int id PK 
        int anio 
        int cuatrimestre "Check(1, 2)"
        int mes
    }

    BI_DIM_SEDE {
        bigint id PK
        NVARCHAR nombre "length: 255"
    }

    BI_DIM_Categoria_Curso {
        bigint id PK
        VARCHAR Categoria_Descripcion "length: 255"
    }

    BI_DIM_Turno_Curso {
        smallint id PK
        VARCHAR Turno_Descripcion "length: 255"
    }

    BI_DIM_ETARIO_ALUMNO {
        smallint id PK
        char RANGO_ETARIO "length: 5"
    }

    BI_DIM_ETARIO_PROFESOR {
        smallint id PK
        char RANGO_ETARIO "length: 10"
    }

    BI_DIM_BLOQUES_SATISFACCION {
        smallint id PK
        CHAR SATISFACCION "length: 20"
    }

    BI_DIM_MEDIO_PAGO {
        smallint id PK
        VARCHAR descripcion "length: 255"
    }

    %% FACTS TABLE
    BI_HECHOS_INSCRIPCION_CURSADA {
        int TIEMPO_ID PK, FK
        bigint SEDE_ID PK, FK
        bigint CATEGORIA_CURSO_ID PK, FK
        bigint TURNO_CURSO_ID PK, FK
        int CANTIDAD_INSCRIPCIONES
    }

    BI_DIM_TIEMPO ||--o{ BI_HECHOS_INSCRIPCION_CURSADA : ""
    BI_DIM_SEDE ||--o{ BI_HECHOS_INSCRIPCION_CURSADA : ""
    BI_DIM_Categoria_Curso ||--o{ BI_HECHOS_INSCRIPCION_CURSADA : ""
    BI_DIM_Turno_Curso ||--o{ BI_HECHOS_INSCRIPCION_CURSADA : ""

    BI_HECHOS_INSCRIPCION_RECHAZADAS{
        int TIEMPO_ID PK, FK
        bigint SEDE_ID PK, FK
        int TOTAL_INSCRIPCIONES
        int TOTAL_RECHAZADAS
    }

    BI_DIM_TIEMPO ||--o{ BI_HECHOS_INSCRIPCION_RECHAZADAS : ""
    BI_DIM_SEDE ||--o{ BI_HECHOS_INSCRIPCION_RECHAZADAS : ""

    BI_HECHOS_APROBADOS{
        int TIEMPO_ID PK, FK
        bigint SEDE_ID PK, FK
        int TOTAL_APROBADOS
        int TOTAL_DESAPROBADOS
    }
    
    BI_DIM_TIEMPO ||--o{ BI_HECHOS_APROBADOS : ""
    BI_DIM_SEDE ||--o{ BI_HECHOS_APROBADOS : ""

    BI_HECHOS_FINALIZACION_CURSADA {
        int TIEMPO_ID PK, FK
        bigint CATEGORIA_CURSO_ID PK, FK
        decimal TIEMPO_PROMEDIO_FINALIZACION
    }

    BI_DIM_TIEMPO ||--o{ BI_HECHOS_FINALIZACION_CURSADA : ""
    BI_DIM_Categoria_Curso ||--o{ BI_HECHOS_FINALIZACION_CURSADA : ""

    BI_HECHOS_EXAMEN_FINAL {
        int TIEMPO_ID PK, FK
        bigint SEDE_ID PK, FK
        bigint CATEGORIA_CURSO_ID PK, FK
        smallint RANGO_ETARIO_ALUMNO_ID PK, FK
        decimal TOTAL_NOTAS "length: 10, 2"
        int TOTAL_EXAMENES_DADOS
        int TOTAL_INSCRIPCIONES_FINAL
        %% porcentaje_ausentes: se calcula a partir de total ausentes y total examenes
        %% NOTA_PROMEDIO_FINAL: se calcula a partir de total notas y total examenes
        %% int TOTAL_AUSENTES
    }

    BI_HECHOS_ENCUESTA{
        int TIEMPO_ID PK, FK
        int ETARIO_PROFESOR_ID PK, FK
        smallint BLOQUE_SATISFACCION_ID PK, FK
        bigint SEDE_ID PK, FK
        int TOTAL_ENCUESTAS
        %% TOTAL ENCUESTAS DE TODOS LOS BLOQUES DE SATISFACCION SE HACE EN LA VISTA y ahí
        %% calculo el porcentaje SATISFECHOS o INSATISFECHOS
    }

    BI_HECHOS_PAGOS {
        int TIEMPO_ID PK, FK
        decimal TOTAL_FACTURADO "length: 18, 2"
        decimal TOTAL_PAGADO "length: 18, 2"
        %% decimal TOTAL_ADEUDADO "length: 18, 2" = TOTAL_FACTURADO - TOTAL_PAGADO
        int PAGOS_FUERA_TERMINO
        int TOTAL_PAGOS_EN_TERMINO
    }

    BI_HECHOS_INGRESOS {
        int TIEMPO_ID PK, FK
        bigint CATEGORIA_CURSO_ID PK, FK
        bigint SEDE_ID PK, FK
        decimal TOTAL_INGRESOS "length: 18, 2"
    }
    BI_DIM_TIEMPO ||--o{ BI_HECHOS_INGRESOS : ""
    BI_DIM_Categoria_Curso ||--o{ BI_HECHOS_INGRESOS : ""
    BI_DIM_SEDE ||--o{ BI_HECHOS_INGRESOS : ""

    BI_HECHOS_AUSENTISMO_FINAL {
        int TIEMPO_ID PK, FK
        bigint SEDE_ID PK, FK
        int TOTAL_INSCRIPCIONES
        int TOTAL_AUSENTES
    }

     BI_DIM_TIEMPO ||--o{ BI_HECHOS_EXAMEN_FINAL : ""
    BI_DIM_Categoria_Curso ||--o{ BI_HECHOS_EXAMEN_FINAL : ""
    BI_DIM_ETARIO_ALUMNO ||--o{ BI_HECHOS_EXAMEN_FINAL : ""

    BI_DIM_TIEMPO ||--o{ BI_HECHOS_AUSENTISMO_FINAL : ""
    BI_DIM_SEDE ||--o{ BI_HECHOS_AUSENTISMO_FINAL : ""

    BI_DIM_TIEMPO ||--o{ BI_HECHOS_ENCUESTA : ""
    BI_DIM_ETARIO_PROFESOR ||--o{ BI_HECHOS_ENCUESTA : ""
    BI_DIM_BLOQUES_SATISFACCION ||--o{ BI_HECHOS_ENCUESTA : ""
    BI_DIM_SEDE ||--o{ BI_HECHOS_ENCUESTA : ""

    BI_DIM_TIEMPO ||--o{ BI_HECHOS_PAGOS : ""